"""
Adapter to unify interaction between AI Context Engine and Atlassian APIs.
"""

from .rest_client import XrayRestClient

class ContextAdapter:
    def __init__(self, config):
        self.client = XrayRestClient(
            base_url=config["base_url"],
            client_id=config["client_id"],
            client_secret=config["client_secret"]
        )

    def create_test_from_context(self, epic_data):
        """Generate and create test case automatically"""
        summary = f"Test for Epic: {epic_data['summary']}"
        description = f"Generated by AI Context Engine\n\nContext:\n{epic_data['description']}"
        return self.client.create_test_case(
            project_key=epic_data["project_key"],
            summary=summary,
            description=description
        )
